/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.9
 * Generated at: 2023-06-27 15:17:23 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.user;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;

public final class cart_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<title>Cart</title>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"../css/cart.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
	
	String email = (String)session.getAttribute("userid");

	Class.forName("oracle.jdbc.driver.OracleDriver");
	Connection con = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:xe","system","nikhil");
	
	PreparedStatement ps = con.prepareStatement("select * from cart where email=?");
	ps.setString(1, email);
	ResultSet rs = ps.executeQuery();
	//rs.next();
	//String tableValue = rs.getString(5);
	//System.out.println("tableValue: "+tableValue);
	System.out.println("email: "+email);
	
	if(rs.next() == false){

      out.write("\t\t<script>\r\n");
      out.write("\t\talert(\"Cart is empty...\");\r\n");
      out.write("\t\tsetTimeout(function() { window.location.href = '../user/home.jsp'; } , 100);\r\n");
      out.write("\t\t</script>\r\n");
	}
	else{

      out.write("\r\n");
      out.write("<div class=\"layout\">\r\n");
      out.write("<center>\r\n");
      out.write("<div class=\"display\">\r\n");
      out.write("<div>Displaying products from the cart...</div>\r\n");
      out.write("\t<table>\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t<td>Cid</td>\r\n");
      out.write("\t<td>Subcategory</td>\r\n");
      out.write("\t<td>Price</td>\r\n");
      out.write("\t<td>Quantity</td>\r\n");
      out.write("\t</tr>\r\n");

 ps = con.prepareStatement("select * from cart where email=?");
ps.setString(1, email);
 rs = ps.executeQuery();
while(rs.next()){ 
      out.write("\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t<td>");
      out.print(rs.getString(1));
      out.write("</td>\r\n");
      out.write("\t<td>");
      out.print(rs.getString(2));
      out.write("</td>\r\n");
      out.write("\t<td>");
      out.print(rs.getString(3));
      out.write("</td>\r\n");
      out.write("\t<td>");
      out.print(rs.getString(4));
      out.write("</td>\r\n");
      out.write("\t</tr>\r\n");
} 
      out.write("\r\n");
      out.write("\t</table>\r\n");
      out.write("\t\r\n");
      out.write("<span></span>\r\n");
      out.write("<div>Deleting products from the cart...</div>\r\n");
      out.write("<form action=\"cartDelete.jsp\" method=\"post\" name=\"cartDelete\">\r\n");
      out.write("\t<table>\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t<td><input type=\"text\" name=\"cid\" placeholder=\"Enter cid...\"/></td>\r\n");
      out.write("\t<td><input type=\"submit\" value=\"Delete\"/></td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t</table>\r\n");
      out.write("</form>\r\n");
      out.write("<div><a href=\"home.jsp\">Cancel Deleting</a></div>\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("</center>\r\n");
con.close();
}
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
