/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.9
 * Generated at: 2023-06-27 14:00:04 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.user;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;

public final class feedback_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<title>Feedback</title>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"../css/feedback.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body >\r\n");
      out.write("\r\n");
      out.write("<div class=\"center\">\r\n");
      out.write("\r\n");
      out.write("<div align=\"center\">\r\n");
      out.write("</br>\r\n");
  

	String userid = (String)session.getAttribute("userid");
	if(userid == null){
      out.write("\r\n");
      out.write("\t\t<script>\r\n");
      out.write("\t\talert(\"Please login for submitting the feedback...\");\r\n");
      out.write("\t\tsetTimeout(function() { window.location.href = '../user/home.jsp'; } , 100);\r\n");
      out.write("\t\t</script>\r\n");
      out.write("\t");
}
      out.write("\r\n");
      out.write("<form name=\"feedback\" method=\"post\" action=\"feedbackSubmit.jsp\">\r\n");
      out.write("\t<table cellpadding=2 cellspacing=2>\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t<td align=\"center\"><h3>Feedback Page</h3></td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t<td align=\"center\">\r\n");
      out.write("\t<textarea name=\"feedback\" rows=20 cols=100 placeholder=\"Please enter your feedbacks...\">\r\n");
      out.write("\t</textarea>\r\n");
      out.write("\t</td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t<td align=\"center\"><input type=\"submit\" /></td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t</table>\r\n");
      out.write("</form>\r\n");
      out.write("\r\n");
      out.write("<div class=\"scroll\">\r\n");

try{
	Class.forName("oracle.jdbc.driver.OracleDriver");
	Connection con = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:xe","system","nikhil");
	PreparedStatement ps =con.prepareStatement("select * from efeedback");
	ResultSet rs = ps.executeQuery();

      out.write("\r\n");
      out.write("<table border=2px>\r\n");
      out.write("<tr>\r\n");
      out.write("<td align=\"center\" colspan=2 style=\"color:blue; font-size:30px;\"><b>Email</b></td>\r\n");
      out.write("<td align=\"center\" style=\"color:blue; font-size:30px;\"><b>Feedbacks</b></td>\r\n");
      out.write("</tr>\r\n");

while(rs.next())
{

      out.write("\r\n");
      out.write("<tr>\r\n");
      out.write("<td align=\"center\" colspan=2 class=\"fed\">");
      out.print(rs.getString(2));
      out.write("</td>\r\n");
      out.write("<td align=\"center\" class=\"fed\">");
      out.print(rs.getString(3));
      out.write("</td>\r\n");
      out.write("</tr>\r\n");

}
}
catch(Exception e){
	System.out.println(e);
}

      out.write("\r\n");
      out.write("<tr>\r\n");
      out.write("<td colspan=\"3\" align=\"center\"><a href=\"../user/home.jsp\">Go Back</a></td>\r\n");
      out.write("</tr>\r\n");
      out.write("</table>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
