/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.9
 * Generated at: 2023-06-27 14:09:33 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.user;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;

public final class payment_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"../css/payment.css\">\r\n");
      out.write("<script src=\"../js/payment.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");

//if quantity is not selected then redirect to the home page
	String quantity = request.getParameter("quantity");
	String subCategory = request.getParameter("scn");
	
	String userid = (String)session.getAttribute("userid");
	
	session.setAttribute("quantity", quantity);
	System.out.println("quantity "+quantity);
	
	if(quantity.isEmpty() || userid == null){
		response.sendRedirect("../user/home.jsp");
	}

      out.write("\r\n");
      out.write("\t<div class=\"layout\">\r\n");
      out.write("\t  <form action=\"thankYou.jsp\" name=\"paymentPage\" method=\"post\">\r\n");
      out.write("\t\t<div class=\"content\">\r\n");
      out.write("\t\t\t<div class=\"left\">\r\n");
      out.write("\t\t\t<div class=\"heading\">Billing Address</div></br>\r\n");
      out.write("\t\t\t<div>\r\n");
      out.write("\t\t\t<div>Full Name</div><span></span>\r\n");
      out.write("\t\t\t<input type=\"text\" id=\"fullName\" maxlength=\"30\" placeholder=\"Enter your full name\" required />\r\n");
      out.write("\t\t\t</div></br>\r\n");
      out.write("\t\t\t<div>\r\n");
      out.write("\t\t\t<div>Email</div><span></span>\r\n");
      out.write("\t\t\t<input type=\"email\" id=\"email\" placeholder=\"Enter your email\" required />\r\n");
      out.write("\t\t\t</div></br>\r\n");
      out.write("\t\t\t<div>\r\n");
      out.write("\t\t\t<div>Address</div><span></span>\r\n");
      out.write("\t\t\t<input type=\"text\" id=\"address\" placeholder=\"Enter your address\" required />\r\n");
      out.write("\t\t\t</div></br>\r\n");
      out.write("\t\t\t<div>\r\n");
      out.write("\t\t\t<div>City</div><span></span>\r\n");
      out.write("\t\t\t<input type=\"text\" id=\"city\" placeholder=\"Enter your city\" required />\r\n");
      out.write("\t\t\t</div></br>\r\n");
      out.write("\t\t\t<div class=\"gap\">\r\n");
      out.write("\t\t\t<div class=\"leftGap\">\r\n");
      out.write("\t\t\t<div>State</div>\r\n");
      out.write("\t\t\t<input type=\"text\" id=\"state\" placeholder=\"Enter your state\" required />\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"rightGap\">\r\n");
      out.write("\t\t\t<div>Zip Code</div>\r\n");
      out.write("\t\t\t<input type=\"text\" maxlength=\"6\" id=\"zipCode\" placeholder=\"Enter your zip code\" required />\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t</div><span></span>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<div class=\"left\">\r\n");
      out.write("\t\t\t<div class=\"heading\">Payment</div></br>\r\n");
      out.write("\t\t\t<div>\r\n");
      out.write("\t\t\t<div>Accepted Cards</div><span></span>\r\n");
      out.write("\t\t\t <img src=\"../images/cards.png\"> \r\n");
      out.write("\t\t\t</div></br>\r\n");
      out.write("\t\t\t<div>\r\n");
      out.write("\t\t\t<div>Name On Card</div><span></span>\r\n");
      out.write("\t\t\t<input type=\"text\" id=\"nameOnCard\" placeholder=\"Enter your name on card\" required />\r\n");
      out.write("\t\t\t</div></br>\r\n");
      out.write("\t\t\t<div>\r\n");
      out.write("\t\t\t<div>Card Number</div><span></span>\r\n");
      out.write("\t\t\t<input type=\"text\" maxlength=\"16\" id=\"cardNumber\" placeholder=\"Enter your card number\" required />\r\n");
      out.write("\t\t\t</div></br>\r\n");
      out.write("\t\t\t<div>\r\n");
      out.write("\t\t\t<div>Exp Month</div><span></span>\r\n");
      out.write("\t\t\t<input type=\"text\" maxlength=\"2\" id=\"expMonth\" placeholder=\"Enter your expiry month\" required />\r\n");
      out.write("\t\t\t</div></br>\r\n");
      out.write("\t\t\t<div class=\"gap\">\r\n");
      out.write("\t\t\t<div class=\"leftGap\">\r\n");
      out.write("\t\t\t<div>Exp Year</div>\r\n");
      out.write("\t\t\t<input type=\"text\" maxlength=\"2\" id=\"expYear\" placeholder=\"Enter your expiry year\" required />\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"rightGap\">\r\n");
      out.write("\t\t\t<div>CVV</div>\r\n");
      out.write("\t\t\t<input type=\"text\" maxlength=\"3\" id=\"cvv\" placeholder=\"Enter your cvv\" required />\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t</div><span></span>\t\r\n");
      out.write("\t\t\t</div>\t\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"button\">\r\n");
      out.write("\t\t\t<button type=\"submit\" onclick=\"return right();\">Proceed To Checkout</button>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<div class=\"button\">\r\n");
      out.write("\t\t\t<button type=\"button\" onclick=\"window.location.href = 'home.jsp';\">Cancel Payment</button>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
