/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.9
 * Generated at: 2023-06-27 14:40:38 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.user;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;

public final class subCategory_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"../css/subCategory.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div class=\"layout\">\r\n");
      out.write("\t<div class=\"top-space\"></div>\r\n");
      out.write("\t<div class=\"top\">\r\n");
      out.write("\t<nav>\r\n");
      out.write("\t<ul>\r\n");
      out.write("\t<li><a href=\"home.jsp\">Home</a></li>\r\n");
      out.write("\t<div class=\"searchBox\">\r\n");
      out.write("\t<form action=\"../user/searchboxSubmit.jsp\">\r\n");
      out.write("\t<input type=\"search\" size=\"47\" name=\"searchbox\" id=\"searchbox\" placeholder=\"searching...\" align=\"center\"/>\r\n");
      out.write("\t<input type=\"submit\" value=\"Search\"/>\r\n");
      out.write("\t</form>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t");
 
try{	
	String userid = (String)session.getAttribute("userid");
	if(userid == null){
      out.write("\r\n");
      out.write("\t<li><a href=\"signupPage.jsp\">Sign Up</a></li>\r\n");
      out.write("\t");
}
	else{
      out.write("\r\n");
      out.write("\t<div class=\"dropdown\">\r\n");
      out.write("\t<div class=\"dropdownButton\">User</div>\r\n");
      out.write("\t<div class=\"dropdownContent\">\r\n");
      out.write("\t<a href=\"../user/updatePage.jsp\">Account</a>\r\n");
      out.write("\t<a href=\"../user/cart.jsp\">Cart</a>\r\n");
      out.write("\t<a href=\"../user/logoutPage.jsp\">Log Out</a>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t");
}
      out.write("\r\n");
      out.write("\t<li><a href=\"../admin/loginPage.jsp\" target=\"_blank\">Admin</a></li>\r\n");
      out.write("\t</ul>\r\n");
      out.write("\t</nav>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"content\">\r\n");
      out.write("\t<div class=\"left\">\r\n");
      out.write("\t<table>\r\n");
  String scn=request.getParameter("scn"); 
	session.setAttribute("scn", scn);

//	subcategory name as in "scn"
	System.out.println("fhfghgfhgfhgf "+scn);
	
	String email = request.getParameter("email");
	Class.forName("oracle.jdbc.driver.OracleDriver");
	Connection con = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:xe","system","nikhil");
	
	PreparedStatement ps =con.prepareStatement("select distinct category from eproducts");
//	using Distinct sql because it will remove repitition(display on webpage) from database of category coulmn	
	ResultSet categoryResultSet = ps.executeQuery();
	
	String categoryName = "";
	String subCategoryName = "";
	
while(categoryResultSet.next())
{ 	
	categoryName = categoryResultSet.getString(1);

      out.write("\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t<td>\r\n");
      out.write("\t<div class=\"categoryDropdown\">\t\r\n");
      out.write("\t<div class=\"categoryDropdownButton\">\r\n");
      out.write("\t<a href=\"category.jsp?cn=");
      out.print(categoryName);
      out.write('"');
      out.write('>');
      out.print(categoryName);
      out.write("</a>\r\n");
      out.write("\t");
      out.write("\t\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class=\"categoryDropdownContent\">\r\n");

	PreparedStatement ps1 = con.prepareStatement("select subcategory from eproducts where category=?");
	ps1.setString(1, categoryName);
	ResultSet subCategoryResultSet = ps1.executeQuery();
	//query will repeat until above query finished exceuted 
	while(subCategoryResultSet.next())
	{	
		subCategoryName = subCategoryResultSet.getString(1);
	//	System.out.println(i+" "+categoryName+" "+subCategoryName);
	
      out.write("\t\r\n");
      out.write("\t<a href=\"subCategory.jsp?scn=");
      out.print(subCategoryName);
      out.write('"');
      out.write('>');
      out.print(subCategoryName);
      out.write("</a>\r\n");
      out.write("\t");
      out.write(" \t\r\n");
      out.write("\t");
}
      out.write("\r\n");
      out.write("\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t</td>\r\n");
      out.write("\t</tr>\r\n");
 } 
      out.write("\r\n");
      out.write("\t</table>\t\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
//getting the image name from the database and 
  //fetching it from project directory as well
	ps = con.prepareStatement("select image from eproducts where subcategory=?");
	ps.setString(1, scn);
	ResultSet subCategoryImageResultSet = ps.executeQuery();
	subCategoryImageResultSet.next();
	
	String img = subCategoryImageResultSet.getString(1);
	System.out.println(img);
	String uploadPath = "../images/"+img;
	System.out.println("subcategory page: "+uploadPath);

      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t<div class=\"middle\">\r\n");
      out.write("\t<div class=\"image\">\r\n");
      out.write("\t<img src=");
      out.print(uploadPath);
      out.write("  height=\"400\" width=\"600\"/>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t<div class=\"data\"><span></span>\r\n");
      out.write("\t<center>");
      out.print(scn);
      out.write("</center><span></span>\r\n");
      out.write("\t");

	PreparedStatement ps2 =con.prepareStatement("select data, price from eproducts where subcategory=?");
	ps2.setString(1, scn);
	ResultSet subCategoryDataResultSet = ps2.executeQuery();
	subCategoryDataResultSet.next();
	String data = subCategoryDataResultSet.getString(1);
	String price = subCategoryDataResultSet.getString(2);
	System.out.println("data "+data);
	System.out.println("price "+price);
	
      out.write('\r');
      out.write('\n');
      out.write('	');
      out.print(data);
      out.write("\r\n");
      out.write("\t<span></span>\r\n");
      out.write("\t");
      out.print(price);
      out.write("\r\n");
      out.write("\t<span></span></div>\r\n");
      out.write("\t\r\n");
      out.write("\t");

	PreparedStatement ps3 =con.prepareStatement("select quantity from eproducts where subcategory=?");
	ps3.setString(1, scn);
	ResultSet subCategoryQuantityResultSet = ps3.executeQuery();
	subCategoryQuantityResultSet.next();
	String quantity = subCategoryQuantityResultSet.getString(1);
	//session.setAttribute("quantity", quantity);
	//System.out.println("quantity "+quantity);
	
      out.write("\r\n");
      out.write("\t\t");

	if(Integer.parseInt(quantity) <= 1){
	
      out.write("\r\n");
      out.write("\t<center><div>Out of Stock</div></center>\r\n");
      out.write("\t");
} 
	else{
      out.write("\r\n");
      out.write("\t<div class=\"purchase\">\r\n");
      out.write("\t<div class=\"atc\"><a href=\"addToCart.jsp?scn=");
      out.print(scn);
      out.write("\">Add to Cart</a></div>\r\n");
      out.write("\t\r\n");
      out.write("\t<form action=\"../user/payment.jsp\" method=\"post\">\r\n");
      out.write("\t<div class=\"range\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<input type=\"range\" id=\"range\" min=\"1\" max=\"");
      out.print(quantity);
      out.write("\" oninput=\"this.nextElementSibling.value = this.value\" required/>\r\n");
      out.write("\t<input type=\"text\" name=\"quantity\" readonly>\r\n");
      out.write("\t<input type=\"hidden\" name=\"scn\" value=\"");
      out.print(scn);
      out.write("\"/>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class=\"ptb\">\r\n");
      out.write("\t<input type=\"submit\" value=\"Proceed to Buy\"/>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t</form>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t");
} 
		con.close();
}
catch(Exception e){
	System.out.println(e);
}
	
      out.write("\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"right\">\r\n");
      out.write("\t<table>\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t<td><a href=\"../user/feedback.jsp\">Feedback</a></td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t<td><a href=\"../user/query.jsp\">Query</a></td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t</table>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
