/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.9
 * Generated at: 2023-06-27 15:45:50 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.admin;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;

public final class adminControl_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("<title>Admin Control Page</title>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"../css/adminControl.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\t<!-- edit or update/ insert or add/ delete\r\n");
      out.write("   \t\t create ( already have a DB in oracle) -->\r\n");
      out.write("\r\n");
      out.write("<div class=\"layout\">\r\n");
      out.write("  <div class=\"heading\">Admin Controls</div>\r\n");
      out.write("  <div class=\"inner\">\r\n");
      out.write("\t<table class=\"insert\">\r\n");
      out.write("\t<form action=\"adminControlInsertSubmit.jsp\" name=\"insertForm\" method=\"post\">\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t<td colspan=\"5\">Adding the new products...</td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t<td>Category</td>\r\n");
      out.write("\t<td>Sub-Category</td>\r\n");
      out.write("\t<td>Quantity</td>\r\n");
      out.write("\t<td>Price</td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t<td><input type=\"text\" name=\"insertCategory\" id=\"insertCategory\"></td>\r\n");
      out.write("\t<td><input type=\"text\" name=\"insertSubCategory\" id=\"insertSubCategory\"></td>\r\n");
      out.write("\t<td><input type=\"text\" name=\"insertQuantity\" id=\"insertQuantity\" maxlength=\"30\"/></td>\r\n");
      out.write("\t<td><input type=\"text\" name=\"insertPrice\" id=\"insertPrice\" maxlength=\"30\"/></td>\r\n");
      out.write("\t<td><input type=\"submit\" value=\"Insert\"></td>\t\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t</form>\r\n");
      out.write("\t</table>\r\n");
      out.write("\t\r\n");
      out.write("\t<table class=\"insert\">\r\n");
      out.write("\t<form action=\"imageEpid.jsp\" name=\"imageForm\" method=\"post\">\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t<td colspan=\"5\">Adding the image to the new products...</td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t<td>Epid</td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t<td><input type=\"text\" name=\"epid\" id=\"epid\" maxlength=\"30\"/></td>\r\n");
      out.write("\t<td><input type=\"submit\" value=\"Next\"/></td>\t\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t</form>\r\n");
      out.write("\t</table>\r\n");
      out.write("\t\r\n");
      out.write("\t<table class=\"insert\">\r\n");
      out.write("\t<form action=\"dataEpid.jsp\" name=\"imageForm\" method=\"post\">\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t<td colspan=\"5\">Adding the data to the new products...</td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t<td>Epid</td>\r\n");
      out.write("\t<td>Data</td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t<td><input type=\"text\" name=\"epid\" id=\"epid\" maxlength=\"30\"/></td>\r\n");
      out.write("\t<td><input type=\"text\" name=\"data\" id=\"data\"/></td>\r\n");
      out.write("\t<td><input type=\"submit\" value=\"Insert\"/></td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t</form>\r\n");
      out.write("\t</table>\r\n");
      out.write("\t\r\n");
      out.write("\t<div>\r\n");
      out.write("\t<table class=\"update\">\r\n");
      out.write("\t<form action=\"adminControlUpdateSubmit.jsp\" name=\"updateForm\" method=\"post\">\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t<td colspan=\"6\">Details of the existing products...</td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t<td>Epid</td>\r\n");
      out.write("\t<td>Category</td>\r\n");
      out.write("\t<td>Sub-Category</td>\r\n");
      out.write("\t<td>Quantity</td>\r\n");
      out.write("\t<td>Price</td>\r\n");
      out.write("\t<td>Image</td>\r\n");
      out.write("\t</tr>\r\n");
	
	String adminid = (String)session.getAttribute("adminid");
	try{
	Class.forName("oracle.jdbc.driver.OracleDriver");
	Connection con = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:xe","system","nikhil");
	
	PreparedStatement ps = con.prepareStatement("select * from eproducts");
	ResultSet rs = ps.executeQuery();
while(rs.next()){

      out.write("\t<tr>\r\n");
      out.write("\t<td>");
      out.print(rs.getString(1));
      out.write("</td>\r\n");
      out.write("\t<td>");
      out.print(rs.getString(2));
      out.write("</td>\r\n");
      out.write("\t<td>");
      out.print(rs.getString(3));
      out.write("</td>\r\n");
      out.write("\t<td>");
      out.print(rs.getString(4));
      out.write("</td>\r\n");
      out.write("\t<td>");
      out.print(rs.getString(5));
      out.write("</td>\r\n");
      out.write("\t<td>");
      out.print(rs.getString(6));
      out.write("</td>\r\n");
      out.write("\t</tr>\r\n");
}
      out.write("\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t<td colspan=\"6\">Updating the changes in the existing products...</td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t<td>Epid</td>\r\n");
      out.write("\t<td>Category</td>\r\n");
      out.write("\t<td>Sub-Category</td>\r\n");
      out.write("\t<td>Quantity</td>\r\n");
      out.write("\t<td>Price</td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t<td><input type=\"text\"  name=\"updateEpid\" id=\"updateEpid\" maxlength=\"30\"></td>\r\n");
      out.write("\t<td><input type=\"text\"  name=\"updateCategory\" id=\"updateCategory\"></td>\r\n");
      out.write("\t<td><input type=\"text\"  name=\"updateSubCategory\" id=\"updateSubCategory\"></td>\r\n");
      out.write("\t<td><input type=\"text\"  name=\"updateQuantity\" id=\"updateQuantity\" maxlength=\"30\"></td>\r\n");
      out.write("\t<td><input type=\"text\"  name=\"updatePrice\" id=\"updatePrice\" maxlength=\"30\"></td>\t\r\n");
      out.write("\t<td><input type=\"submit\" value=\"Update\"/></td>\t\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t</form>\r\n");
      out.write("\t</table>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t<table class=\"delete\">\r\n");
      out.write("\t<form action=\"adminControlDeleteSubmit.jsp\" name=\"deleteForm\" method=\"post\">\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t<td colspan=\"3\">Deleting the existing product...</td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t<td>Epid</td>\r\n");
      out.write("\t<td><input type=\"text\"  name=\"deleteEpid\" id=\"deleteEpid\" maxlength=\"30\"></td>\r\n");
      out.write("\t<td><input type=\"submit\" value=\"Delete\"/></td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t</form>\r\n");

} 
catch(Exception e){
	System.out.println(e);
}

      out.write("\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t<td colspan=\"3\"><a href=\"access.jsp\">Go Back</a></td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t</table>\t\r\n");
      out.write("  </div>\t\r\n");
      out.write("</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
