/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.9
 * Generated at: 2023-06-09 18:18:13 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.admin;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;

public final class updatePage_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<title>Update Details</title>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"../css/updatePage.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body align=\"center\" background=\"1.jpg\">\r\n");

try
{
String adminid = (String)session.getAttribute("adminid");
if(adminid != null)
{
	Class.forName("oracle.jdbc.driver.OracleDriver");
	Connection con = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:xe","system","nikhil");
	PreparedStatement ps = con.prepareStatement("select * from eadmin where email=? ");
	ps.setString(1, adminid);
	ResultSet rs = ps.executeQuery();
	if(rs.next()){

      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"outer\">\r\n");
      out.write("<div class=\"heading\">\r\n");
      out.write("Update Page\r\n");
      out.write("</div>\r\n");
      out.write("<div class=\"inner\">\r\n");
      out.write("\t<table cellpadding=\"2\">\r\n");
      out.write("\t<form action=\"updatePageSubmit.jsp\" name=\"signupPage\" onsubmit=\"return right();\" method=\"post\"\">\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t<td>First Name</td>\r\n");
      out.write("\t<td><input type=\"text\" value=\"");
      out.print(rs.getString(2));
      out.write("\" name=\"firstName\" id=\"firstName\" placeholder=\"your first name\" maxlength=\"30\" required/></td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t<td>Middle Name</td>\r\n");
      out.write("\t<td><input type=\"text\" value=\"");
      out.print(rs.getString(3));
      out.write("\" name=\"middleName\" id=\"middleName\" placeholder=\"your middle name\" maxlength=\"30\" required/></td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t<td>Last Name</td>\r\n");
      out.write("\t<td><input type=\"text\" value=\"");
      out.print(rs.getString(4));
      out.write("\" name=\"lastName\" id=\"lastName\" placeholder=\"your last name\" maxlength=\"30\" required/></td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t<td>Gender</td>\r\n");
      out.write("\t<td>\r\n");
      out.write("\t<select name=\"gender\" id=\"gender\" style=\"width: 100%;\" required>\r\n");
      out.write("    <option value=\"male\">Male</option>\r\n");
      out.write("    <option value=\"female\">Female</option>\r\n");
      out.write("    </select>\r\n");
      out.write("\t</td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t<td>Mobile Number</td>\r\n");
      out.write("\t<td><input type=\"text\" value=\"");
      out.print(rs.getString(6));
      out.write("\" name=\"mobileNumber\" id=\"mobileNumber\" maxlength=\"10\" placeholder=\"your mobile number\" required></td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t<td>Address</td>\r\n");
      out.write("\t<td><input type=\"text\" value=\"");
      out.print(rs.getString(7));
      out.write("\" name=\"address\" id=\"address\" placeholder=\"your address\" maxlength=\"50\" required/></td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t<td>E-mail</td>\r\n");
      out.write("\t<td><input type=\"email\" value=\"");
      out.print(rs.getString(8));
      out.write("\" name=\"email\" id=\"email\"  placeholder=\"your email\" maxlength=\"50\" required/></td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t<td>Password</td>\r\n");
      out.write("\t<td><input type=\"password\" value=\"");
      out.print(rs.getString(9));
      out.write("\" name=\"password\" id=\"password\"  placeholder=\"your password\" maxlength=\"15\" required/></td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t<td colspan=\"2\"><input type=\"submit\" value=\"Update Account\"/></td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t</form>\r\n");
      out.write("\t</table>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
 	
  }
	else
	{
		System.out.println("Record is not found");
	}
}	
}
catch(Exception e)
{
	System.out.println(e);
}	
      out.write("\r\n");
      out.write("<script src=\"../js/adminUpdatePage.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
