/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.9
 * Generated at: 2023-06-06 16:59:05 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"../css/home.css\">\r\n");
      out.write("<title>Home</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div class=\"layout\">\r\n");
      out.write("\t<div class=\"topspace\"></div>\r\n");
      out.write("\t<div class=\"top\">\r\n");
      out.write("\t<nav>\r\n");
      out.write("\t<ul>\r\n");
      out.write("\t<li><a href=\"home.jsp\">Home</a></li>\r\n");
      out.write("\t<div class=\"searchBox\">\r\n");
      out.write("\t<input type=\"search\" size=\"47\" name=\"searchbox\" id=\"searchbox\" placeholder=\"searching...\" align=\"center\"/>\r\n");
      out.write("\t<button onclick=\"window.location.href = '../user/searchboxSubmit.jsp';\">Search</button>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t");
 
	String userid = (String)session.getAttribute("userid");
	if(userid == null){
      out.write("\r\n");
      out.write("\t<li><a href=\"signupPage.jsp\">Sign Up</a></li>\r\n");
      out.write("\t");
}
	else{
      out.write("\r\n");
      out.write("\t<div class=\"dropdown\">\r\n");
      out.write("\t<div class=\"dropdownButton\">User</div>\r\n");
      out.write("\t<div class=\"dropdownContent\">\r\n");
      out.write("\t<a href=\"updatePage.jsp\">Account</a>\r\n");
      out.write("\t<a href=\"cartPage.jsp\">Cart</a>\r\n");
      out.write("\t<a href=\"logoutPage.jsp\">Log Out</a>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t");
}
      out.write("\r\n");
      out.write("\t<li><a href=\"../admin/loginPage.jsp\" target=\"_blank\">Admin</a></li>\r\n");
      out.write("\t</ul>\r\n");
      out.write("\t</nav>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"content\">\r\n");
      out.write("\t\r\n");
      out.write("\t<div class=\"left\">\r\n");
      out.write("\t<table>\r\n");

	String email = request.getParameter("email");
	Class.forName("oracle.jdbc.driver.OracleDriver");
	Connection con = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:xe","system","nikhil");
	
	PreparedStatement ps =con.prepareStatement("select distinct category from eproducts");
//	using Distinct sql because it will remove repitition(display on webpage) from database of category coulmn	
	ResultSet categoryResultSet = ps.executeQuery();
	
	String categoryName = "";
	String subCategoryName = "";
	
while(categoryResultSet.next())
{ 	
	categoryName = categoryResultSet.getString(1);

      out.write("\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t<td>\r\n");
      out.write("\t<div class=\"categoryDropdown\">\t\r\n");
      out.write("\t<div class=\"categoryDropdownButton\">\r\n");
      out.write("\t<a href=\"category.jsp?cn=");
      out.print(categoryName);
      out.write('"');
      out.write('>');
      out.print(categoryName);
      out.write("</a>\r\n");
      out.write("\t");
      out.write("\t\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class=\"categoryDropdownContent\">\r\n");

	PreparedStatement ps1 =con.prepareStatement("select subcategory from eproducts where category=?");
	ps1.setString(1, categoryName);
	ResultSet subCategoryResultSet = ps1.executeQuery();
	//query will repeat until above query finished exceuted 
	while(subCategoryResultSet.next())
	{	
		subCategoryName = subCategoryResultSet.getString(1);
	//	System.out.println(i+" "+categoryName+" "+subCategoryName);
	
      out.write("\t\r\n");
      out.write("\t<a href=\"subCategory.jsp?scn=");
      out.print(subCategoryName);
      out.write('"');
      out.write('>');
      out.print(subCategoryName);
      out.write("</a>\r\n");
      out.write("\t");
      out.write(" \r\n");
      out.write("\t");
}
      out.write("\r\n");
      out.write("\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t</td>\r\n");
      out.write("\t</tr>\r\n");
 } 
      out.write("\r\n");
      out.write("\t</table>\t\r\n");
      out.write("\t</div><!--end of left-->\r\n");
      out.write("\t\r\n");
      out.write("\t<div class=\"e\">\r\n");
      out.write("\t<div class=\"ss-container\">\r\n");
      out.write("\t<div class=\"mySlides fade\">\r\n");
      out.write("\t<img src=\"../images/a.jpg\" onclick=\"window.location.href = '../user/loginPage.jsp';\" class=\"pics\" />\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class=\"mySlides fade\">\r\n");
      out.write("\t<img src=\"../images/c.jpg\" class=\"pics\" />\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class=\"mySlides fade\">\r\n");
      out.write("\t<img src=\"../images/dbx2.jpeg\" class=\"pics\" />\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class=\"mySlides fade\">\r\n");
      out.write("\t<img src=\"../images/e.jpg\" class=\"pics\" />\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<a class=\"prev\" onclick=\"plusSlides(-1)\">&#10094;</a> <a class=\"next\" onclick=\"plusSlides(1)\">&#10095;</a>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!--    Putting in the click dots   -->\r\n");
      out.write("\t<div style=\"text-align: center\">\r\n");
      out.write("\t<span class=\"dot\" onclick=\"currentSlide(1)\"></span> <span class=\"dot\"\r\n");
      out.write("\tonclick=\"currentSlide(2)\"></span> <span class=\"dot\"\r\n");
      out.write("\tonclick=\"currentSlide(3)\"></span> <span class=\"dot\"\r\n");
      out.write("\tonclick=\"currentSlide(4)\"></span>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t<div class=\"recentlyView\">\r\n");
      out.write("\t<div>Recently Viewed</div>\r\n");
      out.write("\t<div>\r\n");
      out.write("\t<table>\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t<td><img src=\"../images/a.jpg\" /></td>\r\n");
      out.write("\t<td><img src=\"../images/a.jpg\" /></td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t<td><a href=\"home.jsp\">Home</a></td>\r\n");
      out.write("\t<td><a href=\"home.jsp\">Home</a></td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t<td><img src=\"../images/a.jpg\" /></td>\r\n");
      out.write("\t<td><img src=\"../images/a.jpg\" /></td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t<td><a href=\"home.jsp\">Home</a></td>\r\n");
      out.write("\t<td><a href=\"home.jsp\">Home</a></td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t</table>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t</br>\r\n");
      out.write("\t<div class=\"recentlyView\">\r\n");
      out.write("\t<div>Most Visited</div>\r\n");
      out.write("\t<div>\r\n");
      out.write("\t<table>\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t<td><img src=\"../images/a.jpg\" /></td>\r\n");
      out.write("\t<td><img src=\"../images/a.jpg\" /></td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t<td><a href=\"home.jsp\">Home</a></td>\r\n");
      out.write("\t<td><a href=\"home.jsp\">Home</a></td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t<td><img src=\"../images/a.jpg\" /></td>\r\n");
      out.write("\t<td><img src=\"../images/a.jpg\" /></td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t<td><a href=\"home.jsp\">Home</a></td>\r\n");
      out.write("\t<td><a href=\"home.jsp\">Home</a></td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t</table>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t<div class=\"right\">\r\n");
      out.write("\t<table>\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t<td><a href=\"../admin/feedback.jsp\">Feedback</a></td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t<td><a href=\"home.jsp\">Query</a></td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t</table>\r\n");
      out.write("\t</div><!--   end of right   -->\r\n");
      out.write("\t\r\n");
      out.write("\t</div><!--   end of content   -->\r\n");
      out.write("</div>\t\r\n");
      out.write("<script src=\"../js/home.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
