/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.9
 * Generated at: 2023-05-06 08:49:35 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class test_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"ISO-8859-1\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<style>\r\n");
      out.write("* {\r\n");
      out.write("\tbox-sizing: border-box;\r\n");
      out.write("}\r\n");
      out.write("#slide{\r\n");
      out.write("\twidth:96%;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("* {\r\n");
      out.write("\tbox-sizing: border-box\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".mySlides {\r\n");
      out.write("\tdisplay: none\r\n");
      out.write("}\r\n");
      out.write(".ss-container{\r\n");
      out.write("max-width: 87%;\r\n");
      out.write("position: relative;\r\n");
      out.write("margin: auto;\r\n");
      out.write("border-style: double;\r\n");
      out.write("}\r\n");
      out.write(".slideshow-container {\r\n");
      out.write("\twidth: auto;\r\n");
      out.write("\tposition: relative;\r\n");
      out.write("\tmargin: -10px;\r\n");
      out.write("}\r\n");
      out.write("/* Next & previous buttons */\r\n");
      out.write(".prev, .next {\r\n");
      out.write("\tcursor: pointer;\r\n");
      out.write("\tposition: absolute;\r\n");
      out.write("\ttop: 50%;\r\n");
      out.write("\twidth: auto;\r\n");
      out.write("\tpadding: 16px;\r\n");
      out.write("\tmargin-top: -22px;\r\n");
      out.write("\tcolor: #494B55;\r\n");
      out.write("\tfont-weight: bold;\r\n");
      out.write("\tfont-size: 18px;\r\n");
      out.write("\ttransition: 0.6s ease;\r\n");
      out.write("\tborder-radius: 0 3px 3px 0;\r\n");
      out.write("}\r\n");
      out.write("/* Position the \"next button\" to the right */\r\n");
      out.write(".next {\r\n");
      out.write("\tright: 0;\r\n");
      out.write("\tborder-radius: 3px 0 0 3px;\r\n");
      out.write("}\r\n");
      out.write("/* On hover, add a black background color with a little bit see-through */\r\n");
      out.write(".prev:hover, .next:hover {\r\n");
      out.write("\tbackground-color: rgba(0,0,0,0.8);\r\n");
      out.write("}\r\n");
      out.write("/* Caption text */\r\n");
      out.write(".text {\r\n");
      out.write("\tcolor: #f2f2f2;\r\n");
      out.write("\tfont-size: 15px;\r\n");
      out.write("\tpadding: 8px 12px;\r\n");
      out.write("\tposition: absolute;\r\n");
      out.write("\tbottom: 8px;\r\n");
      out.write("\twidth: 100%;\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("img{\r\n");
      out.write("width: 33vw;\r\n");
      out.write("\theight: 92%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* The dots/bullets/indicators */\r\n");
      out.write(".dot {\r\n");
      out.write("\tcursor: pointer;\r\n");
      out.write("\theight: 13px;\r\n");
      out.write("\twidth: 13px;\r\n");
      out.write("\tmargin: 0 2px;\r\n");
      out.write("\tbackground-color: #bbb;\r\n");
      out.write("\tborder-radius: 50%;\r\n");
      out.write("\tdisplay: inline-block;\r\n");
      out.write("\ttransition: background-color 0.6s ease;\r\n");
      out.write("}\r\n");
      out.write(".active, .dot:hover {\r\n");
      out.write("\tbackground-color: #494B55;\r\n");
      out.write("}\r\n");
      out.write("/* Fading animation */\r\n");
      out.write(".fade {\r\n");
      out.write("\t-webkit-animation-name: fade;\r\n");
      out.write("\t-webkit-animation-duration: 2s;\r\n");
      out.write("\tanimation-name: fade;\r\n");
      out.write("\tanimation-duration: 2s;\r\n");
      out.write("}\r\n");
      out.write("@-webkit-keyframes fade {\r\n");
      out.write("  from {opacity: .4} \r\n");
      out.write("  to {opacity: 1}\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("@keyframes fade {\r\n");
      out.write("  from {opacity: .4} \r\n");
      out.write("  to {opacity: 1}\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* On smaller screens, decrease text size */\r\n");
      out.write("@media only screen and (max-width: 300px) {\r\n");
      out.write("  .text {font-size: 11px}\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".pics\r\n");
      out.write("{\r\n");
      out.write("    border:3px solid #494B55;\r\n");
      out.write("    width:100%;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div class=\"ss-container\">\r\n");
      out.write("                <div class=\"mySlides fade\">\r\n");
      out.write("                    <img src=\"./images/a.jpg\" onclick=\"window.location.href = './user/loginPage.jsp';\" class=\"pics\"/>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"mySlides fade\">\r\n");
      out.write("                    <img src=\"./images/c.jpg\" class=\"pics\"/>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"mySlides fade\">\r\n");
      out.write("                    <img src=\"./images/dbx2.jpeg\" class=\"pics\"/>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"mySlides fade\">\r\n");
      out.write("                    <img src=\"./images/e.jpg\" class=\"pics\"/>\r\n");
      out.write("                </div>\r\n");
      out.write("                <a class=\"prev\" onclick=\"plusSlides(-1)\">&#10094;</a>\r\n");
      out.write("                <a class=\"next\" onclick=\"plusSlides(1)\">&#10095;</a>\r\n");
      out.write("            </div>\r\n");
      out.write("            \r\n");
      out.write("            <!--    Putting in the click dots   -->\r\n");
      out.write("            <div style=\"text-align:center\">\r\n");
      out.write("                <span class=\"dot\" onclick=\"currentSlide(1)\"></span>\r\n");
      out.write("                <span class=\"dot\" onclick=\"currentSlide(2)\"></span>\r\n");
      out.write("                <span class=\"dot\" onclick=\"currentSlide(3)\"></span>\r\n");
      out.write("                <span class=\"dot\" onclick=\"currentSlide(4)\"></span>\r\n");
      out.write("            </div>\r\n");
      out.write("            <script>\r\n");
      out.write("            var slideIndex = 0;\r\n");
      out.write("            showSlides();\r\n");
      out.write("            //add the global timer variable\r\n");
      out.write("            var slides,dots,timer;\r\n");
      out.write("\r\n");
      out.write("            function showSlides() {\r\n");
      out.write("                var i;\r\n");
      out.write("                slides = document.getElementsByClassName(\"mySlides\");\r\n");
      out.write("                dots = document.getElementsByClassName(\"dot\");\r\n");
      out.write("                for (i = 0; i < slides.length; i++) {\r\n");
      out.write("                   slides[i].style.display = \"none\";  \r\n");
      out.write("                }\r\n");
      out.write("                slideIndex++;\r\n");
      out.write("                if (slideIndex> slides.length) {slideIndex = 1}    \r\n");
      out.write("                for (i = 0; i < dots.length; i++) {\r\n");
      out.write("                    dots[i].className = dots[i].className.replace(\" active\", \"\");\r\n");
      out.write("                }\r\n");
      out.write("                slides[slideIndex-1].style.display = \"block\";  \r\n");
      out.write("                dots[slideIndex-1].className += \" active\";\r\n");
      out.write("                //put the timeout in the timer variable\r\n");
      out.write("                timer = setTimeout(showSlides, 4000); // Change image every 8 seconds\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            function plusSlides(position) {\r\n");
      out.write("                //clear/stop the timer\r\n");
      out.write("                clearTimeout(timer);\r\n");
      out.write("                slideIndex +=position;\r\n");
      out.write("                if (slideIndex> slides.length) {slideIndex = 1}\r\n");
      out.write("                else if(slideIndex<1){slideIndex = slides.length}\r\n");
      out.write("                for (i = 0; i < slides.length; i++) {\r\n");
      out.write("                   slides[i].style.display = \"none\";  \r\n");
      out.write("                }\r\n");
      out.write("                for (i = 0; i < dots.length; i++) {\r\n");
      out.write("                    dots[i].className = dots[i].className.replace(\" active\", \"\");\r\n");
      out.write("                }\r\n");
      out.write("                slides[slideIndex-1].style.display = \"block\";  \r\n");
      out.write("                dots[slideIndex-1].className += \" active\";\r\n");
      out.write("                //create a new timer\r\n");
      out.write("                timer = setTimeout(showSlides, 4000);\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            function currentSlide(index) {\r\n");
      out.write("                //clear/stop the timer\r\n");
      out.write("                clearTimeout(timer);\r\n");
      out.write("                if (index> slides.length) {index = 1}\r\n");
      out.write("                else if(index<1){index = slides.length}\r\n");
      out.write("                //set the slideIndex with the index of the function\r\n");
      out.write("                slideIndex = index;\r\n");
      out.write("                for (i = 0; i < slides.length; i++) {\r\n");
      out.write("                   slides[i].style.display = \"none\";  \r\n");
      out.write("                }\r\n");
      out.write("                for (i = 0; i < dots.length; i++) {\r\n");
      out.write("                    dots[i].className = dots[i].className.replace(\" active\", \"\");\r\n");
      out.write("                }\r\n");
      out.write("                slides[index-1].style.display = \"block\";  \r\n");
      out.write("                dots[index-1].className += \" active\";\r\n");
      out.write("                //create a new timer\r\n");
      out.write("                timer = setTimeout(showSlides, 4000);\r\n");
      out.write("            }</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
