/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.9
 * Generated at: 2022-03-04 14:52:16 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class Amnesia_0020The_0020Dark_0020Descent_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<title>Amnesia The Dark Descent</title>\r\n");
      out.write("<script src=\"games.js\"></script>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"games.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body >\r\n");
      out.write("\r\n");
      out.write("<div class=\"table\">\r\n");
      out.write("<table class=\"table1\" cellpadding=\"10\" align=\"center\" border=2px>\r\n");
      out.write("<td> <a href=\"aboutUs.jsp\">Home</a> </td> \r\n");
      out.write("\r\n");

String id = (String)session.getAttribute("id");
if(id==null){

      out.write("\r\n");
      out.write("<td> <a href=\"signUp.jsp\">Sign-Up</a> </td>\r\n");
      out.write("<td> <a href=\"login.jsp\">Log-In</a> </td>\r\n");

}
else{

      out.write("\r\n");
      out.write("<td> <a> Game Inventory</a> </td>\r\n");
      out.write("<td> <a href=\"update.jsp\">Account</a> </td>\r\n");
      out.write("<td> <a href=\"logout.jsp\">Log-Out</a> </td>\r\n");
} 
      out.write("\r\n");
      out.write("</tr>\r\n");
      out.write("</table>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div class=\"left\">\r\n");
      out.write("<table class=\"table2\" border=2px>\r\n");
      out.write("<tr>\r\n");
      out.write("<td align=\"center\" style=\"text-decoration:none; color:white;\"><b>Genres</b></td>\r\n");
      out.write("</tr>\r\n");
      out.write("<tr>\r\n");
      out.write("<td align=\"center\"><a href=\"aboutUs.jsp\">Action</a></td>\r\n");
      out.write("</tr>\r\n");
      out.write("<tr>\r\n");
      out.write("<td align=\"center\"><a href=\"adventure.jsp\">Adventure</a></td>\r\n");
      out.write("</tr>\r\n");
      out.write("<tr>\r\n");
      out.write("<td align=\"center\"><a href=\"strategy.jsp\">Strategy</a></td>\r\n");
      out.write("</tr>\r\n");
      out.write("<tr>\r\n");
      out.write("<td align=\"center\"><a href=\"survival.jsp\">Survival</a></td>\r\n");
      out.write("</tr>\r\n");
      out.write("<tr>\r\n");
      out.write("<td align=\"center\"><a href=\"horror.jsp\">Horror</a></td>\r\n");
      out.write("</tr>\r\n");
      out.write("<tr>\r\n");
      out.write("<td align=\"center\"><a href=\"shooting.jsp\">Shooting</a></td>\r\n");
      out.write("</tr>\r\n");
      out.write("</table>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<form action=\"add.jsp\" onsubmit=\"return call()\" method=\"post\">\r\n");
      out.write("<input type=\"hidden\" name=\"gameName\" value=\"Amnesia The Dark Descent\"/>\r\n");
      out.write("<div class=\"center\">\r\n");
      out.write("</br>\r\n");
      out.write("<img src=\"atdd.jpg\">\r\n");
      out.write("<p style=\"font-size:24px;\">\r\n");
      out.write("Amnesia: The Dark Descent is a survival horror adventure video game by Frictional Games, \r\n");
      out.write("released in 2010 for Microsoft Windows, Mac OS X and Linux operating systems, in 2016 for \r\n");
      out.write("the PlayStation 4 platform and in 2018 for the Xbox One. The game features a protagonist \r\n");
      out.write("named Daniel exploring a dark and foreboding castle, while trying to maintain his sanity by \r\n");
      out.write("avoiding monsters and other terrifying obstructions. The game was critically well-received, \r\n");
      out.write("earning two awards from the Independent Games Festival and numerous positive reviews.\r\n");
      out.write("\r\n");
      out.write("Originally released independently via online distribution, the game has since been published \r\n");
      out.write("in retail by 1C Company in Russia and Eastern Europe, as well as THQ in North America. \r\n");
      out.write("A collection of five short stories set in the world of Amnesia, written by Mikael Hedberg and \r\n");
      out.write("illustrated by the game's concept artists, was also made available.  In addition, the game's \r\n");
      out.write("soundtrack is available for purchase and a free content expansion Justine has been released, \r\n");
      out.write("as well as many fan-made expansions and stories for its unique \"Custom Story\" game mode. \r\n");
      out.write("The Amnesia Collection â which contains The Dark Descent, its Amnesia: Justine expansion and \r\n");
      out.write("the sequel, A Machine for Pigs â was released for PlayStation 4 on 22 November 2016, and for \r\n");
      out.write("Xbox One on 28 September 2018. The same collection was released on the Nintendo Switch on 12 \r\n");
      out.write("September 2019.[10](digital download only from the Nintendo eShop). A second sequel, \r\n");
      out.write("Amnesia: Rebirth, was announced on 6 March 2020, and is scheduled for release in late 2020.\r\n");
      out.write("</p>\r\n");
      out.write("</br>\r\n");
      out.write("<center><iframe width=\"600\" height=\"400\" src=\"https://www.youtube.com/embed/u1nY_5-UrY4?autoplay=1\">\r\n");
      out.write("</iframe></center>\r\n");
      out.write("</br>\t\r\n");
      out.write("<span class=\"span1\">Price: Rs.2000</span>\r\n");
      out.write("<input type=\"hidden\" name=\"price\" value=\"2000\"/>\r\n");
      out.write("<input type=\"submit\" value=\"Purchase\"/>\r\n");
      out.write("<span class=\"span2\">Quantity<input type=\"text\" id=\"quantity\" name=\"quantity\" required maxlength=1 size=1/></span>\r\n");
      out.write("</div>\r\n");
      out.write("</form>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
