/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.9
 * Generated at: 2022-03-03 17:14:22 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class Call_0020of_0020Duty_0020Modern_0020Warfare_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<title>Call of Duty Modern Warfare</title>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"games.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body >\r\n");
      out.write("\r\n");
      out.write("<div class=\"table\">\r\n");
      out.write("<table class=\"table1\" cellpadding=\"10\" align=\"center\" border=2px>\r\n");
      out.write("<td> <a href=\"aboutUs.jsp\">Home</a> </td> \r\n");
      out.write("\r\n");

String id = (String)session.getAttribute("id");
if(id==null){

      out.write("\r\n");
      out.write("<td> <a href=\"signUp.jsp\">Sign-Up</a> </td>\r\n");
      out.write("<td> <a href=\"login.jsp\">Log-In</a> </td>\r\n");

}
else{

      out.write("\r\n");
      out.write("<td> <a> Game Inventory</a> </td>\r\n");
      out.write("<td> <a href=\"update.jsp\">Account</a> </td>\r\n");
      out.write("<td> <a href=\"logout.jsp\">Log-Out</a> </td>\r\n");
} 
      out.write("\r\n");
      out.write("</tr>\r\n");
      out.write("</table>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div class=\"left\">\r\n");
      out.write("<table class=\"table2\" border=2px>\r\n");
      out.write("<tr>\r\n");
      out.write("<td align=\"center\" style=\"text-decoration:none; color:white;\"><b>Genres</b></td>\r\n");
      out.write("</tr>\r\n");
      out.write("<tr>\r\n");
      out.write("<td align=\"center\"><a href=\"aboutUs.jsp\">Action</a></td>\r\n");
      out.write("</tr>\r\n");
      out.write("<tr>\r\n");
      out.write("<td align=\"center\"><a href=\"adventure.jsp\">Adventure</a></td>\r\n");
      out.write("</tr>\r\n");
      out.write("<tr>\r\n");
      out.write("<td align=\"center\"><a href=\"strategy.jsp\">Strategy</a></td>\r\n");
      out.write("</tr>\r\n");
      out.write("<tr>\r\n");
      out.write("<td align=\"center\"><a href=\"survival.jsp\">Survival</a></td>\r\n");
      out.write("</tr>\r\n");
      out.write("<tr>\r\n");
      out.write("<td align=\"center\"><a href=\"horror.jsp\">Horror</a></td>\r\n");
      out.write("</tr>\r\n");
      out.write("<tr>\r\n");
      out.write("<td align=\"center\"><a href=\"shooting.jsp\">Shooting</a></td>\r\n");
      out.write("</tr>\r\n");
      out.write("</table>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<form action=\"add.jsp\">\r\n");
      out.write("<input type=\"hidden\" name=\"gameName\" value=\"Call of Duty Modern Warfare\"/>\r\n");
      out.write("<div class=\"center\">\r\n");
      out.write("</br>\r\n");
      out.write("<img src=\"codmw.jpg\">\r\n");
      out.write("<p style=\"font-size:24px;\">\r\n");
      out.write("Call of Duty: Modern Warfare is a first-person shooter video game developed by Infinity Ward \r\n");
      out.write("and published by Activision. Serving as the sixteenth overall installment in the Call of Duty \r\n");
      out.write("series, as well as a reboot of the Modern Warfare sub-series, it was released on \r\n");
      out.write("October 25, 2019, for Microsoft Windows, PlayStation 4, and Xbox One.\r\n");
      out.write("\r\n");
      out.write("The game takes place in a realistic and modern setting. The campaign follows a CIA officer and \r\n");
      out.write("British SAS forces as they team up with rebels from the fictional country of Urzikstan, \r\n");
      out.write("combating together against Russian forces who have invaded the country. The game's Special \r\n");
      out.write("Ops mode features cooperative play missions that follow up the campaign's story. \r\n");
      out.write("The multiplayer mode supports cross-platform multiplayer and cross-platform progression for \r\n");
      out.write("the first time in the series. It has been reworked for gameplay to be more tactical and \r\n");
      out.write("introduces new features, such as a Realism mode that removes the HUD as well as a form of the \r\n");
      out.write("Ground War mode that now supports 64 players.\r\n");
      out.write("\r\n");
      out.write("Infinity Ward began working on the game soon after the release of their 2016 title Call of \r\n");
      out.write("Duty: Infinite Warfare. They introduced an entirely new engine for the game, which allows for \r\n");
      out.write("new performance enhancements such as more detailed environments and ray-tracing capabilities. \r\n");
      out.write("For the campaign, they took influence from real-life conflicts, such as the Syrian Civil War \r\n");
      out.write("and terrorist incidents that have occurred in London. For the multiplayer, they scrapped the \r\n");
      out.write("franchise's traditional season pass and removed loot boxes, enabling them to distribute free \r\n");
      out.write("post-launch content to the playerbase in the form of \"Seasons\".\r\n");
      out.write("\r\n");
      out.write("The game received a mixed pre-release reception for its mature subject matter, but was \r\n");
      out.write("released to positive reviews with praise for its gameplay, story, multiplayer, and graphics; \r\n");
      out.write("however, some criticized the handling of the campaign's subject matter as well as balancing \r\n");
      out.write("issues in the multiplayer. In addition, there was controversy regarding the single-player \r\n");
      out.write("campaign's depiction of the Russian military.\r\n");
      out.write("</p>\r\n");
      out.write("</br>\r\n");
      out.write("<center><iframe width=\"600\" height=\"400\" src=\"https://www.youtube.com/embed/zu3wZ-_IKrM?autoplay=1\">\r\n");
      out.write("</iframe></center>\r\n");
      out.write("</br>\t\r\n");
      out.write("<span class=\"span1\">Price: Rs.2500</span>\r\n");
      out.write("<input type=\"hidden\" name=\"price\" value=\"2500\"/>\r\n");
      out.write("<input type=\"submit\" value=\"Purchase\"/>\r\n");
      out.write("<span class=\"span2\">Quantity<input type=\"text\" id=\"quantity\" name=\"quantity\" required maxlength=1 size=1/></span>\r\n");
      out.write("</div>\r\n");
      out.write("</form>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
