/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.9
 * Generated at: 2022-03-08 15:09:16 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class DragonBall_0020Xenoverse_00202_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<title>DragonBall Xenoverse 2</title>\r\n");
      out.write("<script src=\"games.js\"></script>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"games.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body >\r\n");
      out.write("\r\n");
      out.write("<div class=\"table\">\r\n");
      out.write("<table class=\"table1\" cellpadding=\"10\" align=\"center\" border=2px>\r\n");
      out.write("<td> <a href=\"aboutUs.jsp\">Home</a> </td> \r\n");
      out.write("\r\n");

String id = (String)session.getAttribute("id");
if(id==null){

      out.write("\r\n");
      out.write("<td> <a href=\"signUp.jsp\">Sign-Up</a> </td>\r\n");
      out.write("<td> <a href=\"login.jsp\">Log-In</a> </td>\r\n");

}
else{

      out.write("\r\n");
      out.write("<td> <a> Game Inventory</a> </td>\r\n");
      out.write("<td> <a href=\"update.jsp\">Account</a> </td>\r\n");
      out.write("<td> <a href=\"logout.jsp\">Log-Out</a> </td>\r\n");
} 
      out.write("\r\n");
      out.write("</tr>\r\n");
      out.write("</table>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div class=\"left\">\r\n");
      out.write("<table class=\"table2\" border=2px>\r\n");
      out.write("<tr>\r\n");
      out.write("<td align=\"center\" style=\"text-decoration:none; color:white;\"><b>Genres</b></td>\r\n");
      out.write("</tr>\r\n");
      out.write("<tr>\r\n");
      out.write("<td align=\"center\"><a href=\"aboutUs.jsp\">Action</a></td>\r\n");
      out.write("</tr>\r\n");
      out.write("<tr>\r\n");
      out.write("<td align=\"center\"><a href=\"adventure.jsp\">Adventure</a></td>\r\n");
      out.write("</tr>\r\n");
      out.write("<tr>\r\n");
      out.write("<td align=\"center\"><a href=\"strategy.jsp\">Strategy</a></td>\r\n");
      out.write("</tr>\r\n");
      out.write("<tr>\r\n");
      out.write("<td align=\"center\"><a href=\"survival.jsp\">Survival</a></td>\r\n");
      out.write("</tr>\r\n");
      out.write("<tr>\r\n");
      out.write("<td align=\"center\"><a href=\"horror.jsp\">Horror</a></td>\r\n");
      out.write("</tr>\r\n");
      out.write("<tr>\r\n");
      out.write("<td align=\"center\"><a href=\"shooting.jsp\">Shooting</a></td>\r\n");
      out.write("</tr>\r\n");
      out.write("</table>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<form action=\"add.jsp\" onsubmit=\"return call()\" method=\"post\">\r\n");
      out.write("<input type=\"hidden\" name=\"gameName\" value=\"DragonBall Xenoverse 2\"/>\r\n");
      out.write("<div class=\"center\">\r\n");
      out.write("</br>\r\n");
      out.write("<img src=\"dbx2.jpeg\">\r\n");
      out.write("<p style=\"font-size:24px;\">\r\n");
      out.write("The game is very similar to its predecessor in terms of gameplay; it is mostly set in a \r\n");
      out.write("series of 3D battle arenas mostly modeled after notable locations in the Dragon Ball \r\n");
      out.write("universe, with the central hub being an expanded version of Toki-Toki City, called Conton \r\n");
      out.write("City. As reported by the creators of the game, Conton City is seven times larger than \r\n");
      out.write("Toki-Toki City. Players are able to freely traverse this new hub world, and in some areas \r\n");
      out.write("are even capable of flying around, however this feature will not be available from start, \r\n");
      out.write("instead being unlocked. Players will also be able to travel to other hubs such as the \r\n");
      out.write("Namekian Village and Frieza's ship. Some skills will have to be learned through masters, \r\n");
      out.write("like the previous game. However, some masters will be found exclusively in these extra hubs. \r\n");
      out.write("Xenoverse 2 is the fourth Dragon Ball video game to feature character customization. Players \r\n");
      out.write("are able to choose from the five races of the first game: Humans, Saiyans, Majins, Namekians \r\n");
      out.write("and Frieza's race. The game also features race-specific quests, minigames and transformations \r\n");
      out.write("(the latter of which was only available to Saiyans in the first game, via the Super Saiyan \r\n");
      out.write("forms). Players also have a much greater role in the story, as some decisions will have to \r\n");
      out.write("be made by them. Multiplayer servers are now able to hold up to 3000 players at once. \r\n");
      out.write("The game also has a training mode called Training School. The player can use different \r\n");
      out.write("kinds of ki blasts (Power, Homing, Rush, Paralyze and Bomb), and the ki blast type depends \r\n");
      out.write("on the player's race or Super Soul. Another interesting element in the game is that players \r\n");
      out.write("will be able to transfer their previous data from Dragon Ball XV 2's predecessor, Dragon \r\n");
      out.write("Ball Xenoverse. This results in the game's details changing in a way that so players will \r\n");
      out.write("be able to see the character known as the Toki Toki City's \"Hero\" in the middle of the \r\n");
      out.write("square. Players also have the choice not to do this, and can choose from a selection of \r\n");
      out.write("pre-made avatars to serve as the \"Hero\".\r\n");
      out.write("</p>\r\n");
      out.write("</br>\r\n");
      out.write("<center><iframe width=\"600\" height=\"400\" src=\"https://www.youtube.com/embed/R7B7ZvcrOXQ?autoplay=1\">\r\n");
      out.write("</iframe></center>\r\n");
      out.write("</br>\t\r\n");
      out.write("<span class=\"span1\">Price: Rs.1000</span>\r\n");
      out.write("<input type=\"hidden\" name=\"price\" value=\"1000\"/>\r\n");
      out.write("<input type=\"submit\" value=\"Purchase\"/>\r\n");
      out.write("<span class=\"span2\">Quantity<input type=\"text\" id=\"quantity\" name=\"quantity\" required maxlength=1 size=1/></span>\r\n");
      out.write("</div>\r\n");
      out.write("</form>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
