/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.9
 * Generated at: 2022-03-03 17:14:03 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class Dreamfall_0020The_0020Longest_0020Journey_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<title>Dreamfall The Longest Journey</title>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"games.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body >\r\n");
      out.write("\r\n");
      out.write("<div class=\"table\">\r\n");
      out.write("<table class=\"table1\" cellpadding=\"10\" align=\"center\" border=2px>\r\n");
      out.write("<td> <a href=\"aboutUs.jsp\">Home</a> </td> \r\n");
      out.write("\r\n");

String id = (String)session.getAttribute("id");
if(id==null){

      out.write("\r\n");
      out.write("<td> <a href=\"signUp.jsp\">Sign-Up</a> </td>\r\n");
      out.write("<td> <a href=\"login.jsp\">Log-In</a> </td>\r\n");

}
else{

      out.write("\r\n");
      out.write("<td> <a> Game Inventory</a> </td>\r\n");
      out.write("<td> <a href=\"update.jsp\">Account</a> </td>\r\n");
      out.write("<td> <a href=\"logout.jsp\">Log-Out</a> </td>\r\n");
} 
      out.write("\r\n");
      out.write("</tr>\r\n");
      out.write("</table>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div class=\"left\">\r\n");
      out.write("<table class=\"table2\" border=2px>\r\n");
      out.write("<tr>\r\n");
      out.write("<td align=\"center\" style=\"text-decoration:none; color:white;\"><b>Genres</b></td>\r\n");
      out.write("</tr>\r\n");
      out.write("<tr>\r\n");
      out.write("<td align=\"center\"><a href=\"aboutUs.jsp\">Action</a></td>\r\n");
      out.write("</tr>\r\n");
      out.write("<tr>\r\n");
      out.write("<td align=\"center\"><a href=\"adventure.jsp\">Adventure</a></td>\r\n");
      out.write("</tr>\r\n");
      out.write("<tr>\r\n");
      out.write("<td align=\"center\"><a href=\"strategy.jsp\">Strategy</a></td>\r\n");
      out.write("</tr>\r\n");
      out.write("<tr>\r\n");
      out.write("<td align=\"center\"><a href=\"survival.jsp\">Survival</a></td>\r\n");
      out.write("</tr>\r\n");
      out.write("<tr>\r\n");
      out.write("<td align=\"center\"><a href=\"horror.jsp\">Horror</a></td>\r\n");
      out.write("</tr>\r\n");
      out.write("<tr>\r\n");
      out.write("<td align=\"center\"><a href=\"shooting.jsp\">Shooting</a></td>\r\n");
      out.write("</tr>\r\n");
      out.write("</table>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<form action=\"add.jsp\">\r\n");
      out.write("<input type=\"hidden\" name=\"gameName\" value=\"Dreamfall The Longest Journey\"/>\r\n");
      out.write("<div class=\"center\">\r\n");
      out.write("</br>\r\n");
      out.write("<img src=\"dtlj.jpg\">\r\n");
      out.write("<p style=\"font-size:24px;\">\r\n");
      out.write("Dreamfall: The Longest Journey, winner of multiple E3 awards as the best game in its genre, \r\n");
      out.write("is the continuation of a saga that began in the award-winning The Longest Journey, considered \r\n");
      out.write("to be one of the finest adventure games ever made. In Dreamfall, players are taken on an epic \r\n");
      out.write("journey of exploration and adventure as they venture through a thrilling and emotional \r\n");
      out.write("storyline. Dreamfall features a fully interactive world where beautiful music, stunning \r\n");
      out.write("graphics, fascinating characters and unparalleled gameplay variety promises to bring the \r\n");
      out.write("adventure genre into a new era. Prepare for a spiritual, fantastic and powerful gaming \r\n");
      out.write("experience.\r\n");
      out.write("</p>\r\n");
      out.write("</br>\r\n");
      out.write("<center><iframe width=\"600\" height=\"400\" src=\"https://www.youtube.com/embed/1AgpbybOhH8?autoplay=1\">\r\n");
      out.write("</iframe></center>\r\n");
      out.write("</br>\t\r\n");
      out.write("<span class=\"span1\">Price: Rs.800</span>\r\n");
      out.write("<input type=\"hidden\" name=\"price\" value=\"800\"/>\r\n");
      out.write("<input type=\"submit\" value=\"Purchase\"/>\r\n");
      out.write("<span class=\"span2\">Quantity<input type=\"text\" id=\"quantity\" name=\"quantity\" required maxlength=1 size=1/></span>\r\n");
      out.write("</div>\r\n");
      out.write("</form>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
