/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.9
 * Generated at: 2022-03-03 18:52:23 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;

public final class purchase_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<title>Purchase Form</title>\r\n");
      out.write("<style>\r\n");
      out.write("\r\n");
      out.write("body\r\n");
      out.write("{\r\n");
      out.write(" background:url(11.jpg);\r\n");
      out.write(" background-size:cover;\r\n");
      out.write(" background-position:center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".center{\r\n");
      out.write("\r\n");
      out.write(" margin-left:150px;\r\n");
      out.write("  width:1226px;\r\n");
      out.write("  height:695px;\r\n");
      out.write("  margin-top:30px;\r\n");
      out.write("  background:rgba(0,0,0,0.5);\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".center div table\r\n");
      out.write("{\r\n");
      out.write("  color:yellow;\r\n");
      out.write("}\r\n");
      out.write("h1\r\n");
      out.write("{\r\n");
      out.write("   color:#56FF33;\r\n");
      out.write("}\r\n");
      out.write(".center div table tr td\r\n");
      out.write("{\r\n");
      out.write("   font-size:35px;\r\n");
      out.write("   text-align:bold;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".submit\r\n");
      out.write("{\r\n");
      out.write("   border:none;\r\n");
      out.write("   outline:none;\r\n");
      out.write("   height:30px;\r\n");
      out.write("   font-size:20px;\r\n");
      out.write("   color:white;\r\n");
      out.write("   background:blue;\r\n");
      out.write("   border-radius:90px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".center input[type=\"text\"], input[type=\"number\"]\r\n");
      out.write("{\r\n");
      out.write("   height:25px;\r\n");
      out.write("   font-size:20px;\r\n");
      out.write("   color:yellow;\r\n");
      out.write("   background-color:green;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".center select\r\n");
      out.write("{\r\n");
      out.write("   height:25px;\r\n");
      out.write("   size:20px;\r\n");
      out.write("   font-size:20px;\r\n");
      out.write("}\r\n");
      out.write("::placeholder\r\n");
      out.write("{\r\n");
      out.write("  color:yellow;\r\n");
      out.write("}\r\n");
      out.write(".center div table tr td select\r\n");
      out.write("{\r\n");
      out.write("  color:yellow;\r\n");
      out.write("  background:green;\r\n");
      out.write("  border:none;\r\n");
      out.write("  height:25px;\r\n");
      out.write("  border-bottom: 1px solid blue;\r\n");
      out.write("  font-size:18px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".center div table tr td select,option\r\n");
      out.write("{\r\n");
      out.write("  background:green;\r\n");
      out.write("  height:25px;\r\n");
      out.write("  font-size:18px;\r\n");
      out.write("}\r\n");
      out.write(".submit:hover\r\n");
      out.write("{\r\n");
      out.write("    cursor:pointer;\r\n");
      out.write("    background: yellow;\r\n");
      out.write("    color:darkgreen;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body >\r\n");
      out.write("\r\n");
      out.write("<div class=\"center\">\r\n");
      out.write("\r\n");
      out.write("<div align=\"center\">\r\n");
      out.write("<table cellspacing=\"8\" cellpadding=\"7\" class=\"table\">\r\n");
      out.write("</br></br>\r\n");
      out.write("<form name=\"signup\" action=\"purchaseSubmit.jsp\" method=\"post\">\r\n");
      out.write("\r\n");
      out.write("<tr>\r\n");
      out.write("<td colspan=2 align=\"center\"><h1>PURCHASE</h1></td>\r\n");
      out.write("</tr>\r\n");
      out.write("\r\n");
      out.write("<tr>\r\n");
      out.write("<td>First Name</td>\r\n");
      out.write("<td><input type=\"text\" name=\"fname\" required/></td>\r\n");
      out.write("</tr>\r\n");
      out.write("\r\n");
      out.write("<tr>\r\n");
      out.write("<td>Last Name</td>\r\n");
      out.write("<td><input type=\"text\" name=\"lname\" required/></td>\r\n");
      out.write("</tr>\r\n");
      out.write("\r\n");
      out.write("<tr>\r\n");
      out.write("<td>Payment Mode</td>\r\n");
      out.write("<td>\r\n");
      out.write("<select id=\"payment\" name=\"payment\">\r\n");
      out.write("<option value=\"Debit Card\">Debit Card</option>\r\n");
      out.write("</select>\r\n");
      out.write("</td>\r\n");
      out.write("</tr>\r\n");
      out.write("\r\n");
      out.write("<tr>\r\n");
      out.write("<td>Card Number</td>\r\n");
      out.write("<td>\r\n");
      out.write("<input type=\"text\" id=\"cardNumber\" name=\"cardNumber\" maxlength=\"16\" size=16 autocomplete=\"off\" placeholder=\"Enter card number\" required/>\r\n");
      out.write("</td>\r\n");
      out.write("</tr>\r\n");
      out.write("\r\n");
      out.write("<tr>\r\n");
      out.write("<td>Valid Until</td>\r\n");
      out.write("<td>\r\n");
      out.write("<input type=\"number\" id=\"month\" name=\"month\" maxlength=\"2\" min=1 max=12 autocomplete=\"off\" placeholder=\"Month\" required/>\r\n");
      out.write("<input type=\"number\" id=\"year\" name=\"year\" maxlength=\"2\" min=2020 max=2030 autocomplete=\"off\" placeholder=\"Year\" required/>\r\n");
      out.write("</td>\r\n");
      out.write("</tr>\r\n");
      out.write("\r\n");
      out.write("<tr>\r\n");
      out.write("<td>CVC</td>\r\n");
      out.write("<td>\r\n");
      out.write("<input type=\"number\" id=\"cvc\" name=\"cvc\" maxlength=\"3\" min=100 max=999 autocomplete=\"off\" placeholder=\"CVC\" required/>\r\n");
      out.write("</td>\r\n");
      out.write("</tr>\r\n");
      out.write("\r\n");
      out.write("<tr>\r\n");
      out.write("<td>Address</td>\r\n");
      out.write("<td>\r\n");
      out.write("<input type=\"text\" id=\"address\" name=\"address\" maxlength=\"20\" size=16 autocomplete=\"off\" placeholder=\"Enter your address\" required/>\r\n");
      out.write("</td>\r\n");
      out.write("</tr>\r\n");
      out.write("\r\n");
      out.write("<tr>\r\n");
      out.write("<td align=\"center\" colspan=3><input class=\"submit\" type=\"submit\" value=\"Purchase\"/></td>\r\n");
      out.write("</tr>\r\n");
      out.write("\r\n");
      out.write("</form>\r\n");
      out.write("\r\n");
      out.write("</table>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
