/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.9
 * Generated at: 2022-03-22 14:39:42 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;

public final class transaction1_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<title>Transaction Details</title>\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("\r\n");
      out.write("body\r\n");
      out.write("{\r\n");
      out.write(" background-image:url(7.jpg);\r\n");
      out.write(" background-size:cover;\r\n");
      out.write(" background-position:center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".center{\r\n");
      out.write("overflow: scroll;\r\n");
      out.write(" margin-left:150px;\r\n");
      out.write("  width:1226px;\r\n");
      out.write("  height:695px;\r\n");
      out.write("  margin-top:30px;\r\n");
      out.write("  background:rgba(0,0,0,0.5);\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".table tr td\r\n");
      out.write("{\r\n");
      out.write("   color:white;\r\n");
      out.write("   font-size:35px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("h2\r\n");
      out.write("{\r\n");
      out.write("   color:orange;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("button\r\n");
      out.write("{\r\n");
      out.write("   background:none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("a\r\n");
      out.write("{\r\n");
      out.write("   text-decoration:none;\r\n");
      out.write("   font-size:25px; \r\n");
      out.write("   color:yellow;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div class=\"center\">\r\n");

try{
String gameName = (String)session.getAttribute("gameName");	
Class.forName("oracle.jdbc.driver.OracleDriver");
Connection con = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:xe","system","nikhil");

PreparedStatement ps =con.prepareStatement("select max(tran_id) from TRANSACTION");
ResultSet rs3 = ps.executeQuery();
rs3.next();
String t = rs3.getString(1);

PreparedStatement ps1 =con.prepareStatement("Select *  From TRANSACTION where tran_id='"+t+"'");
rs3 = ps1.executeQuery();

      out.write("     <div class=\"c\">\r\n");
      out.write("       <table align=\"center\" class=\"table\" cellpadding=4 cellspacing=4>\r\n");
      out.write("       <tr>\r\n");
      out.write("       <td align=\"center\" colspan=5><h2>Transaction Details</h2></td>\r\n");
      out.write("       </tr>\r\n");
      out.write("       <tr>\r\n");
      out.write("       <td align=\"center\">Transaction ID</td>\r\n");
      out.write("       <td align=\"center\">Payment Mode</td>\r\n");
      out.write("       <td align=\"center\">Amount</td>\r\n");
      out.write("       <td align=\"center\">Date</td>\r\n");
      out.write("       <td align=\"center\">Time</td>\r\n");
      out.write("       </tr>\r\n");

while(rs3.next())
{
      out.write("\r\n");
      out.write("    <tr>\r\n");
      out.write("    <td align=\"center\">");
      out.print(rs3.getString(1));
      out.write("</td>\r\n");
      out.write("    <td align=\"center\">");
      out.print(rs3.getString(2));
      out.write("</td>\r\n");
      out.write("    <td align=\"center\">");
      out.print(rs3.getString(3));
      out.write("</td>\r\n");
      out.write("    <td align=\"center\">");
      out.print(rs3.getString(4));
      out.write("</td>\r\n");
      out.write("    <td align=\"center\">");
      out.print(rs3.getString(5));
      out.write("</td>\r\n");
      out.write("    </tr>\r\n");
}

      out.write("\r\n");
      out.write("<tr>\r\n");
      out.write("<td colspan=5 align=\"center\"> \r\n");
      out.write("<br>\r\n");
      out.write("<button onclick=\"call()\">\r\n");
if(gameName.equals("Amnesia The Dark Descent")) 
      out.write("\r\n");
      out.write("<a href=\"https://gamerpeace.com/wp-content/uploads/2020/12/gamerpeace.com-55A6511.zip\" download>\r\n");
if(gameName.equals("DragonBall Xenoverse 2")) 
      out.write("\r\n");
      out.write("<a href=\"https://gamerpeace.com/wp-content/uploads/2020/12/gamerpeace.com-55A6511.zip\" download>\r\n");
      out.write("<span id=\"change\">Download Your Game</span></a>\r\n");
      out.write("</button>\r\n");
      out.write("</td><script>\r\n");
      out.write("function call(){\r\n");
      out.write("document.write('<body style=\" background-image:url(7.jpg); background-size:cover; background-position:center; background-attachment: fixed; \">');\r\n");
      out.write("document.write('<center><div style=\" background:rgba(0,0,0,0.5); width:70%; font-size:30px; color:white; margin-top:356px\">');\r\n");
      out.write("document.write('<table style=\"font-size:30px;\"><tr><td align=\"center\" ><a  style=\"text-decoration:none; color:yellow;\" href=\"aboutUs.jsp\">Home</a></td></tr></table>');\r\n");
      out.write("document.write('</div></center></body>');\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("</tr>\r\n");
      out.write("</table>\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");

con.close();
}
catch(Exception e){
	out.println(e);
}

      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
