/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.9
 * Generated at: 2021-12-21 16:00:40 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;

public final class update_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<title>Account Settings</title>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"userUpdate.css\">\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body align=\"center\" background=\"1.jpg\">\r\n");

try
{
String id = (String)session.getAttribute("id");
if(id!=null)
{
	String email = (String)session.getAttribute("id");
	Class.forName("oracle.jdbc.driver.OracleDriver");
	Connection con = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:xe","system","nikhil");
	PreparedStatement ps = con.prepareStatement("Select * From GI Where EMAIL=? ");
	ps.setString(1, email);
	ResultSet rs = ps.executeQuery();
	if(rs.next()){

      out.write("\r\n");
      out.write("\r\n");
      out.write("<table class=\"table\" align=\"center\">\r\n");
      out.write("<form name=\"update\" action=\"update1.jsp\" method=\"post\">\r\n");
      out.write("\r\n");
      out.write("<tr>\r\n");
      out.write("<td align=\"center\" colspan=2><h1>UPDATE</h1></td>\r\n");
      out.write("</tr>\r\n");
      out.write("\r\n");
      out.write("<tr>\t\r\n");
      out.write("<td>First Name</td>\r\n");
      out.write("<td><input type=\"text\" id=\"fname\" name=\"fname\" maxlength=\"20\" value=\"");
      out.print(rs.getString(2));
      out.write("\" required /></td>\r\n");
      out.write("</tr>\r\n");
      out.write("\r\n");
      out.write("<tr>\r\n");
      out.write("<td>Last Name</td>\r\n");
      out.write("<td><input type=\"text\" id=\"lname\" name=\"lname\" maxlength=\"20\" value=\"");
      out.print(rs.getString(3));
      out.write("\" required/></td>\r\n");
      out.write("</tr>\r\n");
      out.write("\r\n");
      out.write("<tr>\r\n");
      out.write("<td>E-mail</td>\r\n");
      out.write("<td><input type=\"email\" id=\"email\" name=\"email\" value=\"");
      out.print(rs.getString(4));
      out.write("\" required/></td>\r\n");
      out.write("</tr>\r\n");
      out.write("\r\n");
      out.write("<tr>\r\n");
      out.write("<td>Password</td>\r\n");
      out.write("<td><input type=\"text\" name=\"pswd\" value=\"");
      out.print(rs.getString(5));
      out.write("\" required/></td>\r\n");
      out.write("</tr>\r\n");
      out.write("\r\n");
      out.write("<tr>\r\n");
      out.write("<td>Security Question</td>\r\n");
      out.write("<td>\r\n");
      out.write("<select id=\"security\" name=\"security\">\r\n");
      out.write("<option value=\"What is your favourite color\">What is your favourite color</option>\r\n");
      out.write("<option value=\"What is your favourite tv show\">What is your favourite tv show</option>\r\n");
      out.write("</select>\r\n");
      out.write("</td>\r\n");
      out.write("</tr>\r\n");
      out.write("\r\n");
      out.write("<tr>\r\n");
      out.write("<td></td>\r\n");
      out.write("<td>\r\n");
      out.write("<input type=\"text\" id=\"answer\" name=\"answer\" value=\"");
      out.print(rs.getString(7));
      out.write("\" maxlength=\"20\" required/>\r\n");
      out.write("</td>\r\n");
      out.write("</tr>\r\n");
      out.write("\r\n");
      out.write("</br>\r\n");
      out.write("<tr>\r\n");
      out.write("<td align=\"center\" colspan=2><input type=\"submit\" value=\"Update\" /></td>\r\n");
      out.write("</tr>\r\n");
      out.write("</form>\r\n");
      out.write("</table>\r\n");
 	
  }
	else
	{
		out.println("Record is not found");
	}
}	
}
catch(Exception e)
{
	out.println(e);
}	
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
